### ISSUE TITLE
Text field always gets ignore_above keyword

### ISSUE THREAD

**Issue by tomasn4a** [jayzeng/scrapy-elasticsearch#73]
Hi,

Every time I save a text field to ES, the mapping has the following structure:

```
"text": {
                  "type": "text",
                  "fields": {
                     "keyword": {
                        "type": "keyword",
                        "ignore_above": 256
                     }
                  }
               }
```
Meaning I cannot search for any text that appears after 256 characters.

Is there any way of avoiding this? Thanks very much in advance!

**Comment by jayzeng** [comment]
@tomasn4a sorry for the late reply, you need to re-create your index mapping. https://www.elastic.co/blog/changing-mapping-with-zero-downtime has some good info
