### ISSUE TITLE
Unique key is tuple if using items

### ISSUE THREAD

**Issue by sorenjacobi** [jayzeng/scrapy-elasticsearch#75]
If I am using items for parsing scrapy responses, the unique key when retrieved from the item is a tuple, and process_unique_key() will raise an exception. This can easily be fixed by changing line 94 in scrapyelasticsearch.py

From
        if isinstance(unique_key, list):
To
        if isinstance(unique_key, (list,tuple)):

**Comment by jayzeng** [comment]
Thanks @sorenjacobi, https://github.com/jayzeng/scrapy-elasticsearch/commit/a2c9baf6d96c69f195014ae5ab25c3e36c253fe5 has the change
