### ISSUE TITLE
BulkIndexError

### ISSUE THREAD

**Issue by abc16810** [jayzeng/scrapy-elasticsearch#77]
BulkIndexError: (u'1 document(s) failed to index.', [{u'create': {u'status': 400, u'_type': u'jd_comment_test', u'_index': u'jd_comment-2018-05-26', u'error': {u'reason': u'Field [_id] is defined twice in [jd_comment_test]', u'type': u'illegal_argument_exception'}

How can I solve this problem?

**Comment by jayzeng** [comment]
@abc16810 sorry for the late response, problem is _id is defined twice in jb_comment_test (exactly what the error message says ``` {u'reason': u'Field [_id] is defined twice in [jd_comment_test]```).
